<?php

return [
    'admin_email' => 'info@its-center.ru',
    'shop_name' => 'ИТС-Центр',
	'shop_description' => 'Магазин шин, дисков, фильтров',
	'og_logo' => 'Logo_round_1200.jpg',
    'pagination' => 20,
    'smtp_host' => 'smtp.beget.com',
    'smtp_port' => '2525',
    'smtp_protocol' => '',
    'smtp_login' => 'info@its-center.ru',
    'smtp_password' => 'UB*6mTSY',
	'imap_host' => 'imap.beget.com',
    'imap_port' => '993',
    'imap_login' => 'info@its-center.ru',
    'imap_password' => 'UB*6mTSY',
    'img_width' => 600,
    'img_height' => 600,
	'mini_img_width' => 250,
    'mini_img_height' => 250,
    'gallery_width' => 600,
    'gallery_height' => 600,
	'mini_gallery_width' => 250,
    'mini_gallery_height' => 250,
	'img_width_brand' => 250,
    'img_height_brand' => 250,
	'img_width_filter' => 250,
    'img_height_filter' => 250,
	'img_width_content' => 1400,
    'img_height_content' => 460,
	'ftp_server' => 'shinaspec.beget.tech',
	'ftp_login' => 'shinaspec_its',
    'ftp_pass' => 'lsDV8&b4',
	'ftp_port' => '21',
	'time_active_link' => '3600',
	'sql_user' => 'shinaspec_its',
	'sql_pass' => 'r*cS8hTq',
    'sql_db' => 'shinaspec_its',
	'sql_host' => 'localhost',
];